//! Frozen `/v2` post-quantum golden vectors (X-Wing hybrid seal).
//!
//! Replays `vectors/pq_hpke_seal_v2.json` (the shared `warren-vectors`
//! submodule at the repo root; generated by
//! `examples/gen_pq_hpke_vectors_v2.rs`), the single source of truth read
//! directly rather than a local duplicate copy. Pins, byte-for-byte, the
//! X-Wing recipient key derivation, the forward setup frame, the reverse reply
//! frame, and the signed PQ exit descriptor. Any drift in the HKDF key
//! schedule, the PQ AAD, the frame layout, or the PQ signing payload flips
//! these bytes.
//!
//! Only compiled with `--features pq-hpke`.
#![cfg(feature = "pq-hpke")]

use ed25519_dalek::{Signer, SigningKey, VerifyingKey};
use serde::Deserialize;
use warrenguard_multihop::{
    ExitDescriptorSigned, ExitId, PqAvailability, PqClientSession, PqExitSession,
    XWingRecipientSecretKey, encode_frame_v2, exit_descriptor_signing_payload_pq, negotiate_pq,
    verify_exit_descriptor_pq,
};

#[derive(Deserialize)]
struct Vectors {
    recipient: Recipient,
    encaps: Encaps,
    forward_setup: ForwardSetup,
    reverse_reply: ReverseReply,
    exit_descriptor_pq: DescriptorPq,
}

#[derive(Deserialize)]
struct Recipient {
    mlkem768_d_seed_hex: String,
    mlkem768_z_seed_hex: String,
    x25519_sk_seed_hex: String,
    mlkem768_ek_hex: String,
    x25519_pubkey_hex: String,
}

#[derive(Deserialize)]
struct Encaps {
    mlkem768_m_seed_hex: String,
    x25519_ephemeral_seed_hex: String,
}

#[derive(Deserialize)]
struct ForwardSetup {
    exit_id_hex: String,
    epoch: u32,
    seq: u64,
    payload_hex: String,
    encapsulated_key_hex: String,
    pq_ct_hex: String,
    aead_tag_hex: String,
    ciphertext_hex: String,
    frame_bytes_hex: String,
}

#[derive(Deserialize)]
struct ReverseReply {
    epoch: u32,
    seq: u64,
    payload_hex: String,
    aead_tag_hex: String,
    ciphertext_hex: String,
    frame_bytes_hex: String,
}

#[derive(Deserialize)]
struct DescriptorPq {
    operational_signing_key_seed_hex: String,
    operational_pubkey_hex: String,
    dns_disabled: bool,
    signing_payload_hex: String,
    signature_hex: String,
    descriptor_json: String,
}

fn h(s: &str) -> Vec<u8> {
    hex::decode(s).expect("hex")
}
fn h32(s: &str) -> [u8; 32] {
    h(s).try_into().expect("32 bytes")
}
fn h16(s: &str) -> [u8; 16] {
    h(s).try_into().expect("16 bytes")
}

fn load() -> Vectors {
    let path = format!(
        "{}/../../vectors/pq_hpke_seal_v2.json",
        env!("CARGO_MANIFEST_DIR")
    );
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!("read vectors/pq_hpke_seal_v2.json: {e}; run `git submodule update --init`")
    });
    serde_json::from_str(&raw).expect("parse pq vectors")
}

#[test]
fn forward_setup_frame_is_byte_for_byte_frozen() {
    let v = load();
    let (_sk, pk) = XWingRecipientSecretKey::derive_deterministic(
        &h32(&v.recipient.mlkem768_d_seed_hex),
        &h32(&v.recipient.mlkem768_z_seed_hex),
        &h32(&v.recipient.x25519_sk_seed_hex),
    );
    // The derived recipient material must match the frozen public bytes.
    assert_eq!(pk.mlkem768_ek_bytes(), h(&v.recipient.mlkem768_ek_hex));
    assert_eq!(pk.x25519_pubkey(), &h32(&v.recipient.x25519_pubkey_hex));

    let exit_id = ExitId::from_bytes(h16(&v.forward_setup.exit_id_hex));
    let client = PqClientSession::new_deterministic(
        &pk,
        exit_id,
        &h32(&v.encaps.mlkem768_m_seed_hex),
        &h32(&v.encaps.x25519_ephemeral_seed_hex),
    )
    .expect("client");
    let frame = client
        .seal_setup(
            &h(&v.forward_setup.payload_hex),
            v.forward_setup.epoch,
            v.forward_setup.seq,
        )
        .expect("seal_setup");

    assert_eq!(
        frame.encapsulated_key.as_slice(),
        h(&v.forward_setup.encapsulated_key_hex),
        "ct_X drifted"
    );
    assert_eq!(frame.pq_ct, h(&v.forward_setup.pq_ct_hex), "ct_M drifted");
    assert_eq!(
        frame.aead_tag.as_slice(),
        h(&v.forward_setup.aead_tag_hex),
        "aead tag drifted"
    );
    assert_eq!(
        frame.ciphertext,
        h(&v.forward_setup.ciphertext_hex),
        "ciphertext drifted"
    );
    assert_eq!(
        encode_frame_v2(&frame).expect("encode"),
        h(&v.forward_setup.frame_bytes_hex),
        "encoded /v2 frame bytes drifted from the frozen vector"
    );
}

#[test]
fn exit_decapsulates_and_reverse_reply_is_frozen() {
    let v = load();
    let (sk, _pk) = XWingRecipientSecretKey::derive_deterministic(
        &h32(&v.recipient.mlkem768_d_seed_hex),
        &h32(&v.recipient.mlkem768_z_seed_hex),
        &h32(&v.recipient.x25519_sk_seed_hex),
    );
    let exit_id = ExitId::from_bytes(h16(&v.forward_setup.exit_id_hex));
    let exit = PqExitSession::new(
        &sk,
        &h32(&v.forward_setup.encapsulated_key_hex),
        &h(&v.forward_setup.pq_ct_hex),
        exit_id,
    )
    .expect("exit session");

    let reply = exit
        .seal_response(
            &h(&v.reverse_reply.payload_hex),
            v.reverse_reply.epoch,
            v.reverse_reply.seq,
        )
        .expect("seal_response");
    assert_eq!(reply.aead_tag.as_slice(), h(&v.reverse_reply.aead_tag_hex));
    assert_eq!(reply.ciphertext, h(&v.reverse_reply.ciphertext_hex));
    assert_eq!(
        encode_frame_v2(&reply).expect("encode"),
        h(&v.reverse_reply.frame_bytes_hex),
        "reverse /v2 frame bytes drifted"
    );
}

#[test]
fn pq_descriptor_signing_payload_and_signature_are_frozen() {
    let v = load();
    let op = SigningKey::from_bytes(&h32(&v.exit_descriptor_pq.operational_signing_key_seed_hex));
    assert_eq!(
        op.verifying_key().to_bytes(),
        h32(&v.exit_descriptor_pq.operational_pubkey_hex)
    );

    let exit_id = ExitId::from_bytes(h16(&v.forward_setup.exit_id_hex));
    let payload = exit_descriptor_signing_payload_pq(
        exit_id,
        &h32(&v.recipient.x25519_pubkey_hex),
        v.exit_descriptor_pq.dns_disabled,
        &h(&v.recipient.mlkem768_ek_hex),
    );
    assert_eq!(
        payload,
        h(&v.exit_descriptor_pq.signing_payload_hex),
        "PQ signing payload layout drifted"
    );
    assert_eq!(
        op.sign(&payload).to_bytes().as_slice(),
        h(&v.exit_descriptor_pq.signature_hex),
        "PQ signature drifted"
    );

    // The serialized descriptor round-trips and verifies under the PQ context.
    let descriptor: ExitDescriptorSigned =
        serde_json::from_str(&v.exit_descriptor_pq.descriptor_json).expect("descriptor json");
    let op_pub = VerifyingKey::from_bytes(&h32(&v.exit_descriptor_pq.operational_pubkey_hex))
        .expect("op pubkey");
    verify_exit_descriptor_pq(&op_pub, &descriptor).expect("pq descriptor verifies");
    assert_eq!(
        negotiate_pq(&op_pub, &descriptor, true).expect("negotiate"),
        PqAvailability::Available
    );
}
