//! Push a DNS server config while the tunnel is up.
//!
//! ## Problem
//!
//! The system's `/etc/resolv.conf` typically points at `127.0.0.53`
//! (systemd-resolved) which forwards to a DHCP-provided upstream nameserver.
//! When that upstream sits on the LAN (e.g. `192.168.1.1`), the daemon
//! firewall's "Block LAN" or split-default routes make it unreachable while
//! the tunnel runs.
//!
//! Symptom: `ping 8.8.8.8` works (literal IP via tunnel) but
//! `curl ifconfig.me` fails with "Could not resolve host".
//!
//! ## Solution
//!
//! While the tunnel runs, write a minimal `/etc/resolv.conf` pointing at a
//! DNS server **routed through the tunnel** (e.g. `9.9.9.9` Quad9
//! recommended, `1.1.1.1` Cloudflare, `8.8.8.8` Google). Restore the
//! original at teardown.
//!
//! ## Exit-side DNS resolver
//!
//! A Warren exit serves DNS on the TUN gateway IP `10.66.0.1:53` via a
//! recursive resolver (e.g. kresd) deployed alongside the exit binary,
//! so `--push-dns 10.66.0.1` and `--push-dns 9.9.9.9` both
//! work. A daemon whose DNS config defaults to the tunnel gateway
//! needs no user configuration at all.
//!
//! ## Platforms
//!
//! Linux only (`/etc/resolv.conf` plain text). macOS uses
//! `scutil --dns` / `networksetup`, Windows uses `netsh` - pending.

use std::net::Ipv4Addr;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

const RESOLV_CONF_PATH: &str = "/etc/resolv.conf";
const RESOLV_CONF_BACKUP_PATH: &str = "/etc/resolv.conf.warrenguard.bak";

/// Build the `/etc/resolv.conf` content from a list of DNS servers. Pure
/// (= testable). Minimal format: one `nameserver <ip>` per line + a Warren
/// marker comment.
#[must_use]
pub fn build_resolv_conf(dns_servers: &[Ipv4Addr]) -> String {
    let mut out =
        String::from("# Generated by warrenguard (--push-dns) - restored at tunnel teardown.\n");
    for ip in dns_servers {
        out.push_str(&format!("nameserver {ip}\n"));
    }
    out
}

/// RAII guard: backs up the existing `/etc/resolv.conf` then writes the new
/// config. On async drop (via `uninstall`), restores the backup.
#[derive(Debug)]
pub struct DnsPushGuard {
    resolv_conf_path: PathBuf,
    backup_path: PathBuf,
    installed: bool,
}

impl DnsPushGuard {
    /// Install the DNS push for `dns_servers`. Linux only; errors elsewhere.
    ///
    /// # Errors
    ///
    /// - `dns_servers` empty
    /// - I/O on `/etc/resolv.conf` (= insufficient privileges)
    /// - Backup already present (= conflict with another instance)
    pub fn install(dns_servers: &[Ipv4Addr]) -> Result<Self> {
        if dns_servers.is_empty() {
            anyhow::bail!("--push-dns requires at least one DNS server IP");
        }
        Self::install_with_paths(
            dns_servers,
            Path::new(RESOLV_CONF_PATH),
            Path::new(RESOLV_CONF_BACKUP_PATH),
        )
    }

    /// Test-only variant with explicit paths. Lets us exercise install
    /// without touching the system `/etc`.
    pub(crate) fn install_with_paths(
        dns_servers: &[Ipv4Addr],
        resolv_conf: &Path,
        backup: &Path,
    ) -> Result<Self> {
        if dns_servers.is_empty() {
            anyhow::bail!("--push-dns requires at least one DNS server IP");
        }

        // If a backup already exists, a previous install crashed without
        // cleanup. Refuse to overwrite to avoid losing the original.
        if backup.exists() {
            anyhow::bail!(
                "DNS backup file already exists at {} - \
                 a previous --push-dns session crashed without cleanup. \
                 Inspect manually + remove backup before re-running.",
                backup.display()
            );
        }

        // systemd-resolved setups ship /etc/resolv.conf as a symlink
        // into /run/systemd/resolve/. Writing *through* the link would
        // mutate the stub file in place (racing systemd-resolved, which
        // rewrites it) and a follow-the-link write is also what made
        // the push non-atomic. The atomic rename below replaces the
        // LINK itself with a regular file; surface that loudly because
        // the restore puts back the original CONTENT, not the symlink.
        let is_symlink = std::fs::symlink_metadata(resolv_conf)
            .map(|m| m.file_type().is_symlink())
            .unwrap_or(false);
        if is_symlink {
            tracing::warn!(
                path = %resolv_conf.display(),
                "resolv.conf is a symlink (systemd-resolved style); replacing \
                 the link with a regular file while the tunnel runs. uninstall \
                 restores the original CONTENT as a regular file, not the \
                 symlink - re-link manually (e.g. `ln -sf \
                 ../run/systemd/resolve/stub-resolv.conf /etc/resolv.conf`) if \
                 systemd-resolved should own it again"
            );
        }

        // Read through the link on purpose: the *content* the system
        // resolves with today is what the backup must preserve.
        let original = std::fs::read_to_string(resolv_conf)
            .with_context(|| format!("read {}", resolv_conf.display()))?;
        std::fs::write(backup, &original)
            .with_context(|| format!("write backup {}", backup.display()))?;

        let new_content = build_resolv_conf(dns_servers);
        atomic_write(resolv_conf, &new_content)
            .with_context(|| format!("write {}", resolv_conf.display()))?;

        tracing::info!(
            "Warren DNS push installed: {} -> {} servers (backup at {})",
            resolv_conf.display(),
            dns_servers.len(),
            backup.display()
        );

        Ok(Self {
            resolv_conf_path: resolv_conf.to_path_buf(),
            backup_path: backup.to_path_buf(),
            installed: true,
        })
    }

    /// Restore the original content. Idempotent: when the backup is missing
    /// (already restored or previous run killed), it is a no-op.
    pub fn uninstall(mut self) -> Result<()> {
        if !self.backup_path.exists() {
            tracing::warn!(
                "DNS backup absent at {} - skip restore (probably already done)",
                self.backup_path.display()
            );
            self.installed = false;
            return Ok(());
        }
        let original = std::fs::read_to_string(&self.backup_path)
            .with_context(|| format!("read backup {}", self.backup_path.display()))?;
        atomic_write(&self.resolv_conf_path, &original)
            .with_context(|| format!("restore {}", self.resolv_conf_path.display()))?;
        std::fs::remove_file(&self.backup_path)
            .with_context(|| format!("remove backup {}", self.backup_path.display()))?;
        self.installed = false;
        tracing::info!(
            "Warren DNS push uninstalled: restored {} from backup",
            self.resolv_conf_path.display()
        );
        Ok(())
    }
}

/// Atomically replace `path` with `content`: write a sibling temp file,
/// then `rename(2)` it over the destination. The rename is atomic on
/// POSIX, so a concurrent reader (libc resolver, systemd) never
/// observes a half-written resolv.conf, and a crash mid-write leaves
/// the original intact. When `path` is a symlink, the rename replaces
/// the LINK itself with a regular file instead of following it.
fn atomic_write(path: &Path, content: &str) -> Result<()> {
    let mut tmp_name = path.file_name().map_or_else(
        || std::ffi::OsString::from("resolv.conf"),
        std::ffi::OsStr::to_os_string,
    );
    tmp_name.push(".warren-tmp");
    let tmp = path.with_file_name(tmp_name);
    std::fs::write(&tmp, content).with_context(|| format!("write temp {}", tmp.display()))?;
    if let Err(e) = std::fs::rename(&tmp, path) {
        // Best-effort temp cleanup so a failed rename does not litter
        // /etc with stale temp files on every retry.
        let _ = std::fs::remove_file(&tmp);
        return Err(e)
            .with_context(|| format!("atomic rename {} -> {}", tmp.display(), path.display()));
    }
    Ok(())
}

impl Drop for DnsPushGuard {
    fn drop(&mut self) {
        if self.installed {
            // Best-effort sync restore: avoid leaving the system without DNS
            // if the user hits Ctrl+C before `uninstall().await`.
            if self.backup_path.exists() {
                if let Ok(original) = std::fs::read_to_string(&self.backup_path) {
                    let _ = atomic_write(&self.resolv_conf_path, &original);
                    let _ = std::fs::remove_file(&self.backup_path);
                    tracing::warn!(
                        "DnsPushGuard dropped without uninstall - \
                         best-effort restore from {} done",
                        self.backup_path.display()
                    );
                } else {
                    tracing::error!(
                        "DnsPushGuard drop: failed to read backup {}, \
                         /etc/resolv.conf may be left in pushed state!",
                        self.backup_path.display()
                    );
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ip(s: &str) -> Ipv4Addr {
        s.parse().unwrap()
    }

    #[test]
    fn build_resolv_conf_emits_one_nameserver_per_ip() {
        let s = build_resolv_conf(&[ip("1.1.1.1"), ip("8.8.8.8")]);
        assert!(s.contains("nameserver 1.1.1.1"));
        assert!(s.contains("nameserver 8.8.8.8"));
        let lines: Vec<&str> = s.lines().filter(|l| l.starts_with("nameserver")).collect();
        assert_eq!(lines.len(), 2);
    }

    #[test]
    fn build_resolv_conf_single_server() {
        let s = build_resolv_conf(&[ip("1.1.1.1")]);
        assert!(s.contains("nameserver 1.1.1.1"));
        // Marker required for traceability and post-crash detection.
        assert!(
            s.contains("warrenguard"),
            "must include the marker for traceability"
        );
    }

    #[test]
    fn install_rejects_empty_dns_list() {
        let tmp = tempfile_dir();
        let resolv = tmp.join("resolv.conf");
        let backup = tmp.join("resolv.conf.bak");
        std::fs::write(&resolv, "nameserver 8.8.4.4\n").unwrap();
        let res = DnsPushGuard::install_with_paths(&[], &resolv, &backup);
        assert!(res.is_err(), "must reject empty DNS list");
        assert!(!backup.exists(), "no backup created on error");
    }

    #[test]
    fn install_writes_new_config_and_backups_old() {
        let tmp = tempfile_dir();
        let resolv = tmp.join("resolv.conf");
        let backup = tmp.join("resolv.conf.bak");
        let original = "nameserver 192.168.1.1\n";
        std::fs::write(&resolv, original).unwrap();

        let guard = DnsPushGuard::install_with_paths(&[ip("1.1.1.1")], &resolv, &backup)
            .expect("install OK");

        assert_eq!(std::fs::read_to_string(&backup).unwrap(), original);
        let new = std::fs::read_to_string(&resolv).unwrap();
        assert!(new.contains("nameserver 1.1.1.1"));
        assert!(!new.contains("192.168.1.1"));

        guard.uninstall().expect("uninstall OK");
    }

    #[test]
    fn install_refuses_when_backup_already_exists() {
        // Crash case: a previous install failed and left a backup behind.
        // Don't overwrite or we lose the original.
        let tmp = tempfile_dir();
        let resolv = tmp.join("resolv.conf");
        let backup = tmp.join("resolv.conf.bak");
        std::fs::write(&resolv, "nameserver A\n").unwrap();
        std::fs::write(&backup, "nameserver ORIGINAL\n").unwrap();

        let res = DnsPushGuard::install_with_paths(&[ip("1.1.1.1")], &resolv, &backup);
        assert!(res.is_err(), "must refuse to overwrite existing backup");
        assert_eq!(std::fs::read_to_string(&resolv).unwrap(), "nameserver A\n");
        assert_eq!(
            std::fs::read_to_string(&backup).unwrap(),
            "nameserver ORIGINAL\n"
        );
    }

    #[test]
    fn uninstall_restores_original_and_removes_backup() {
        let tmp = tempfile_dir();
        let resolv = tmp.join("resolv.conf");
        let backup = tmp.join("resolv.conf.bak");
        let original = "nameserver 192.168.1.1\nsearch local\n";
        std::fs::write(&resolv, original).unwrap();

        let guard = DnsPushGuard::install_with_paths(&[ip("1.1.1.1")], &resolv, &backup)
            .expect("install OK");
        guard.uninstall().expect("uninstall OK");

        assert_eq!(std::fs::read_to_string(&resolv).unwrap(), original);
        assert!(
            !backup.exists(),
            "backup file must be removed after uninstall"
        );
    }

    #[test]
    fn drop_without_uninstall_restores_via_backup() {
        // Regression guard: if the user Ctrl-Cs before uninstall().await,
        // the synchronous `Drop` must best-effort restore so the system
        // isn't left without DNS.
        let tmp = tempfile_dir();
        let resolv = tmp.join("resolv.conf");
        let backup = tmp.join("resolv.conf.bak");
        let original = "nameserver 192.168.1.1\n";
        std::fs::write(&resolv, original).unwrap();

        {
            let _guard = DnsPushGuard::install_with_paths(&[ip("1.1.1.1")], &resolv, &backup)
                .expect("install OK");
        }

        assert_eq!(std::fs::read_to_string(&resolv).unwrap(), original);
        assert!(!backup.exists(), "backup removed by drop");
    }

    #[test]
    fn install_leaves_no_temp_file_residue() {
        // The atomic write goes through a sibling `.warren-tmp` file +
        // rename; a leftover temp file would accumulate on every
        // tunnel start and signal a broken rename path.
        let tmp = tempfile_dir();
        let resolv = tmp.join("resolv.conf");
        let backup = tmp.join("resolv.conf.bak");
        std::fs::write(&resolv, "nameserver 192.168.1.1\n").unwrap();

        let guard = DnsPushGuard::install_with_paths(&[ip("1.1.1.1")], &resolv, &backup)
            .expect("install OK");
        let residue: Vec<_> = std::fs::read_dir(&tmp)
            .unwrap()
            .filter_map(|e| e.ok().map(|e| e.file_name().to_string_lossy().into_owned()))
            .filter(|name| name.contains("warren-tmp"))
            .collect();
        assert!(
            residue.is_empty(),
            "temp residue after install: {residue:?}"
        );
        guard.uninstall().expect("uninstall OK");
    }

    #[cfg(unix)]
    #[test]
    fn install_replaces_a_symlinked_resolv_conf_with_a_regular_file() {
        // systemd-resolved layout: /etc/resolv.conf is a symlink into
        // /run. Writing through the link would mutate the stub target
        // in place (raced/undone by systemd-resolved); the install must
        // replace the LINK with a regular file and leave the target
        // untouched.
        let tmp = tempfile_dir();
        let target = tmp.join("stub-resolv.conf");
        let resolv = tmp.join("resolv.conf");
        let backup = tmp.join("resolv.conf.bak");
        let original = "nameserver 127.0.0.53\n";
        std::fs::write(&target, original).unwrap();
        std::os::unix::fs::symlink(&target, &resolv).unwrap();

        let guard = DnsPushGuard::install_with_paths(&[ip("9.9.9.9")], &resolv, &backup)
            .expect("install through a symlinked resolv.conf");

        let meta = std::fs::symlink_metadata(&resolv).unwrap();
        assert!(
            !meta.file_type().is_symlink(),
            "the symlink must be replaced by a regular file - writing \
             through it would race systemd-resolved"
        );
        assert!(
            std::fs::read_to_string(&resolv)
                .unwrap()
                .contains("nameserver 9.9.9.9"),
            "pushed content lands at the resolv.conf path"
        );
        assert_eq!(
            std::fs::read_to_string(&target).unwrap(),
            original,
            "the symlink TARGET (systemd-resolved's stub) is untouched"
        );
        assert_eq!(
            std::fs::read_to_string(&backup).unwrap(),
            original,
            "the backup preserves the content the system resolved with"
        );

        guard.uninstall().expect("uninstall OK");
        let meta = std::fs::symlink_metadata(&resolv).unwrap();
        assert!(
            !meta.file_type().is_symlink(),
            "documented behavior: restore yields a regular file with the \
             original CONTENT, not a re-created symlink (warned at install)"
        );
        assert_eq!(std::fs::read_to_string(&resolv).unwrap(), original);
    }

    /// Build an isolated temp dir per test. Avoids the `tempfile` dep to
    /// keep things minimal. Cleanup is best-effort: if a test panics the
    /// tmp dir is left behind but doesn't break anything.
    ///
    /// The `COUNTER` is a static shared by all tests in the same process
    /// (the `cargo test` run-thread). Making it function-local resulted
    /// in `n = 0` always, and two parallel tests landing on the same
    /// system-clock nanosecond would hit the same path → flaky `EEXIST`.
    fn tempfile_dir() -> PathBuf {
        use std::sync::atomic::{AtomicU64, Ordering};
        static COUNTER: AtomicU64 = AtomicU64::new(0);
        let pid = std::process::id();
        let n = COUNTER.fetch_add(1, Ordering::SeqCst);
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let path = std::env::temp_dir().join(format!("warren-dns-push-test-{pid}-{nanos}-{n}"));
        std::fs::create_dir_all(&path).unwrap();
        path
    }
}
